version: '3.8'

services:
  database:
    build: ./database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo_app
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init-scripts:/docker-entrypoint-initdb.d
    networks:
      - app-network

  database_test:
    build:
      context: ./database
      dockerfile: Dockerfile.test
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo_app_test
    volumes:
      - postgres_data_test:/var/lib/postgresql/data
      - ./database/init-scripts:/docker-entrypoint-initdb.d
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "3002:3002"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@database:5432/todo_app
      - JWT_SECRET=your_jwt_secret
      - PORT=3002
    depends_on:
      - database
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "4200:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  postgres_data_test: