name: Deploy to VM

on:
  push:
    branches: [ main, develop ]
  schedule:
    - cron: '0 22 * * *' # Tous les jours à 22h00 UTC

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Start backend
        run: docker-compose up -d
      - name: Run Cypress tests
        run: npm cy:open
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install backend dependencies
        run: npm install
        working-directory: ./backend

      - name: Run backend tests
        run: npm test
        working-directory: ./backend
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Archive project
        run: |
          tar --warning=no-file-changed -czf app.tar.gz --exclude='.git' . || true

      - name: Check archive
        run: test -f app.tar.gz

      - name: Copy project to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 212.83.131.82
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "app.tar.gz"
          target: "/root/"

      - name: Deploy with docker-compose
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 212.83.131.82
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root
            rm -rf EvalCI-CD
            mkdir EvalCI-CD
            tar xzf app.tar.gz -C EvalCI-CD --strip-components=1
            cd EvalCI-CD
            docker-compose down || true
            docker-compose up -d --build